<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Additional Compiled Classes
    |--------------------------------------------------------------------------
    |
    | Here you may specify additional classes to include in the compiled file
    | generated by the `artisan optimize` command. These should be classes
    | that are included on basically every request into the application.
    |
    */

    'files' => [
        // Reactor Service Providers
        app_path('Providers/ReactorServiceProvider.php'),
        app_path('Providers/AuthServiceProvider.php'),
        app_path('Providers/EventServiceProvider.php'),
        app_path('Providers/RouteServiceProvider.php'),
        app_path('Providers/ValidationRulesServiceProvider.php'),
        app_path('Providers/ViewBindingsServiceProvider.php'),
        app_path('Providers/HtmlBuildersServiceProvider.php'),

        // Kenarkose Service Providers
        base_path('vendor/kenarkose/chronicle/src/ChronicleServiceProvider.php'),
        base_path('vendor/kenarkose/files/src/Provider/FilesServiceProvider.php'),
        base_path('vendor/kenarkose/settlement/src/Provider/Laravel/SettlementServiceProvider.php'),
        base_path('vendor/kenarkose/sortable/src/SortableServiceProvider.php'),
        base_path('vendor/kenarkose/synthesizer/src/Provider/Laravel/SynthesizerServiceProvider.php'),
        base_path('vendor/kenarkose/tracker/src/TrackerServiceProvider.php'),
        base_path('vendor/kenarkose/transit/src/Provider/TransitServiceProvider.php'),
        base_path('vendor/nuclear/hierarchy/src/Providers/HierarchyServiceProvider.php'),
        base_path('vendor/nuclear/hierarchy/src/Providers/BuilderServiceProvider.php'),

        // External Service Providers
        base_path('vendor/laracasts/flash/src/Laracasts/Flash/FlashServiceProvider.php'),
        base_path('vendor/dimsav/laravel-translatable/src/Translatable/TranslatableServiceProvider.php'),

        // Extension Classes
        //base_path('extension/Site/Providers/SiteExtensionServiceProvider.php'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Compiled File Providers
    |--------------------------------------------------------------------------
    |
    | Here you may list service providers which define a "compiles" function
    | that returns additional files that should be compiled, providing an
    | easy way to get common files from any packages you are utilizing.
    |
    */

    'providers' => [
        //
    ],

];
